src/osiris.erl, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_writer.erl, test/osiris_SUITE.erl
=> Command for updating retention without cluster restart

src/osiris_replica.erl, src/osiris_replica_reader.erl
=> Secure replica listener using a one time token

src/osiris_log.erl
ASCII diagrams are used to represent blocks at the bit level. Fields are not described each beside their type.
=> osiris_log: Update log format specification

src/osiris.hrl, src/osiris_log.erl, src/osiris_replica.erl
=> Add 4 reserved bytes to chunk header

src/osiris.erl, src/osiris_log.erl
file:sendfile only supports tcp, so it needs to be replaced by ssl:send
=> Add TLS support for readers

src/osiris.erl, src/osiris_log.erl, test/osiris_log_SUITE.erl
It allows the transfer of unmodified user log, trailers and all
=> Raw offset mode

Makefile, src/osiris_writer.erl
this should allow for multiple streams to recover in parallel
=> Perform osiris_writer initialisation async

src/osiris_replica_reader.erl
Replace large crash log when writer is unavailable for a smaller warning. It's more than enough to identify the problem and doesn't pollute the logs.
=> Handle startup replica error, better logging

src/osiris_log.erl, test/osiris_log_SUITE.erl
Whilst retaining backwards compatibility.
=> Optionally return header map from read_chunk_parsed

src/osiris_replica.erl, src/osiris_replica_reader.erl, src/osiris_util.erl, test/osiris_SUITE.erl
fixes https://github.com/rabbitmq/osiris/issues/53
=> Add hostname from rabbit @ hostname

src/osiris_writer.erl, test/osiris_SUITE.erl
fixes https://github.com/rabbitmq/osiris/issues/61
=> Fix duplicate confirm order

Makefile, WORKSPACE.bazel, src/osiris_counters.erl
API changes.
Added `osiris_counters:overview/1` for more efficient retrieval of a single counter
=> Seshat 0.3.1

.bazelrc, .github/workflows/erlang.yml, .github/workflows/rabbitmq-oci.yaml, .gitignore, BUILD.bazel, MODULE.bazel, WORKSPACE.bazel, bzl/platforms/BUILD.bazel, bzl/toolchains/BUILD.bazel, user-template.bazelrc
Also switch the bazel build in ci to remote execution with buildbuddy
=> Upgrade to rules_erlang 3.1.0

src/osiris_replica.erl, test/osiris_SUITE.erl
If a replica reader exited but the tcp connection was terminated
on the replica side (some weirder infra policies may close connections)
then the replica would never exit and replication woudl stop.
Now we handle any replica reader exit as fatal and stop, also any
non-normal exit would cause the replica to stop, e.g. if the acceptor
process exited before accepting.
=> Better exit signal handling in replica

.bazelrc, BUILD.bazel, MODULE.bazel, WORKSPACE.bazel
Corresponds to:
- https://github.com/rabbitmq/ra/pull/301
- https://github.com/rabbitmq/rabbitmq-server/pull/5098
=> Use our fork of BCR and the latest rules_erlang

src/osiris_log.erl, test/osiris_log_SUITE.erl
A variety bag of smaller fixed and refactoring around how we handle the `missing_file` throws.
=> File size safety and osiris_log error handling refactoring

src/osiris_replica.erl, src/osiris_replica_reader.erl, src/osiris_writer.erl, test/osiris_SUITE.erl
Which will be useful for stream status inspection.
Also improved a couple of log messages.
=> Add epoch to writer and replica counters

.bazelrc, BUILD.bazel, MODULE.bazel, WORKSPACE.bazel, bzl/BUILD.eunit_formatters
And make dialyzer green in bazel for otp 26
=> Sync the project description to bazel from make

BUILD.bazel, MODULE.bazel
which runs the dialyzer against the test suites
=> Add a new target :dialyze_tests in bazel

.bcr/metadata.template.json, .bcr/presubmit.yml, .bcr/source.template.json, .github/workflows/rabbitmq-oci.yaml, .github/workflows/release.yml, BUILD.bazel, MODULE.bazel, WORKSPACE.bazel
1. tag a commit with the v1.* pattern
2. review and publish the draft release created by the workflow
=> Add a Release workflow that publishes to BCR

.bcr/presubmit.yml, MODULE.bazel, WORKSPACE.bazel
See https://github.com/bazelbuild/bazel-central-registry/pull/840
=> Rename the bazel module to rabbitmq_osiris

.github/workflows/rabbitmq-oci.yaml, MODULE.bazel
it was recently changed in rabbitmq-server main
=> Use the correct module name for osiris in the oci workflow

MODULE.bazel
so that it's a native bazel_dep
=> Use seshat from bazel-central-registry

src/osiris_log.erl, test/osiris_log_SUITE.erl
Where an offset reader on a replica node can try to read a chunk before it has been fully written and cause a crc failure.
This could occur if the replica updated the committed offset before the corresponding chunk has been written. The reader would only check the committed offset before attempting to read a chunk. If partial data was available it would not return end_of_stream as expected but instead fail when the full data section could not be read.
The fix is to check both the committed offset and the last chunk id before attempting a read.
=> Fix offset reader race condition

.github/workflows/publish-rabbitmq-bcr.yml
to the rabbitmq erlang-packages registry
=> Add a workflow that publishes as a bzlmod module

src/osiris_log.erl
After RabbitMQ was shut down abruptily the last index file did not have a segment file. In this state the stream cannot start up and crashes in a cicle. (was reproduced with osiris 1.6.2 but the code looks the same on main)
```
initial call: osiris_writer:init/1
...
reason: {{case_clause,missing_file},
[{gen_batch_server,handle_continue,2,
[{file,"src/gen_batch_server.erl"},
{line,413}]},
```
It was found that the `missing_file` is thrown from `osiris_log:maybe_fix_corrupted_files/1`
In this case just delete the index file as no data of the missing segment file can be recovered. (same as if the segment file would exist but withou any chunks)
It is possible that this is not the correct solution and the last segment file should not be missing at all.
=> Handle one more case of corrupt files at startup

src/osiris_log.erl
To use fewer syscalls as well as reading less data.
=> Optimise osiris_log:recover_tracking/1

src/osiris_replica.erl
If different options are passed to `ssl:listen` from later functions that also accept options, there's a chance errors will occur.
This was discovered by limiting the TLS versions for distributed Erlang to just `'tlsv1.3'`. By doing so, `ssl:listen` was not prepared for a TLS 1.3 connection so the internal ssl gen statem callback module / functions were not set up correctly. This resulted in crashes due to `tls_connection:start` (a non-existent function) being set as the next state function, when it should have been something else.
Related items:
* https://pivotal-io.atlassian.net/browse/RMQFPAS-91
* https://vmware.slack.com/archives/C05L704Q5KL
=> Pass SSL options to ssl:listen

src/osiris.erl, src/osiris_member.erl, src/osiris_replica.erl, src/osiris_server_sup.erl, src/osiris_writer.erl
Make it posible to configure the writer module used
=> Make writer and replica impl modules pluggable

.github/workflows/rabbitmq-oci.yaml
=> Use the latest method of building the RabbitMQ OCI in actions
