src/osiris.erl, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_retention.erl, src/osiris_util.erl, src/osiris_writer.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
Adds a server generated posix timestamp to the chunk format and uses this to implement time based retention and reader attach.
This change breaks the binary format.
=> Add time based retention and attach

src/osiris.erl, src/osiris.hrl, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_writer.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
Offset tracking is implemented as two new chunk types, one for snapshots
that are written every time the writer opens a new segment and one for
delta updates that are written in real time as they come in. The writer
maintains a map of tracking ids to offsets and can be queried for a
given tracking id.
=> implement offset tracking

src/osiris_replica_reader.erl
This is a 'normal' behaviour, which causes a lot of noise on the logs.
A warning and normal stop might be more appropiate for most applications
=> Avoid crash log when a replica stops because the socket is closed

src/osiris.hrl
The domain is `[osiris]`. It allows users of Osiris to filter log messages emitted by this application.
=> osiris.hrl: Add domain to logged messages

src/osiris.erl, src/osiris.hrl, src/osiris_counters.erl, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_server_sup.erl, src/osiris_writer.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
The new counters include:
* Number of segments
* readers: replica readers, offset readers and data readers. The sum of these provides an estimate of the open files on each osiris node. Applications can customise using a tag the counter for each time of offset/data reader they might use.
=> Export list of all tracked offsets & new counters

src/osiris_log.erl, src/osiris_replica.erl, src/osiris_writer.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
When retention "takes-over" an offset reader it is possible that a
segment later than the one currently being read is deleted. When the
offset reader reaches the end of it's current segment and finds the next
segment missing it gets stuck and things it has reached the end of the
stream. This change expands the use of the atomic value for the commit
index to also include the first index in the stream which the reader can
query to ensure it correctly can work out what the next available
segment is.
=> Offset readers handle missing segments

src/osiris.erl, src/osiris_log.erl, src/osiris_writer.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
so that the tracking doesn't always need to be an offset but could be
extended to include timestamps or in flight chunk ids (as is needed for
competing reader tracking).
=> Add support for tracking types

src/osiris_log.erl
We've seen timeouts when connecting consumers to streams that already have data. Even moderate amounts of data, like 0.5GB, could lead to the issue when the client requested to start from an offset towards the tail of the stream. It was because scan_index could take almost a minute to find the right offset to attach to so the connection timed out. This is a faster implementation that avoids jumping through the index file back and forth.
=> Faster implementation of index scanning

.github/workflows/erlang.yml, Makefile, src/osiris_log.erl, test/osiris_SUITE.erl
We've observed performance degradation when there is lots of chunks in a
single segment. That's because the segment and/or its index need to be
scanned in certain situations and reading chunk by chunk is slow.
For now, it's compile-time setting with a default of 256000. We may
change that into a service configuration property in the future, if
needed.
Fixes: https://github.com/rabbitmq/rabbitmq-streams-project/issues/8
=> Add max_segment_size_chunks

src/osiris_log.erl
At least for the current testing phase and initial beta/GA release, it's
useful to see how long some internal operations take in certain
scenarios (large streams, lots of chunks, lots of segments, etc).
=> Log duration of potentially slow operations

src/osiris_log.erl, src/osiris_writer.erl
Without this fix, changes to the retention were applied once
(when retention is updated, it is evaluated immediately) but then
forgotten (reset to what was set in osiris_log:init/1).
=> Persist retention spec changes

src/osiris.hrl, src/osiris_log.erl, test/osiris_log_SUITE.erl
Fixes https://github.com/rabbitmq/rabbitmq-streams-project/issues/4 by adding the chunk type (1 byte) to the index record.
This enables us to search the index file backwards if last chunk is not a user chunk (but e.g. a tracking chunk).
Pros:
* simple
* we know the chunk type in the index record (this enables further use cases in the future: e.g. answering questions like "how many user chunk vs other chunks are in the segment?" or "query first / last chunk type" etc. without having to parse the segment file)
Cons:
* Index record increases from 28 to 29 bytes.
* ~~We might want to remove non user chunks from index anyways to enable binary searches in the index file when client attaches by offset or timestamp.~~
Pair: @mkuratczyk
=> Fix "last offset should find last user chunk" by adding chunk type to index record

src/osiris.erl, src/osiris_log.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
Map compression type to compression algorithms.
Add tests cases for sub batch compression.
When parsing a chunk and we encounter a sub batch that is compressed
returned the batch type instead of the individual entries.
=> Improve sub batch compression support

src/osiris_log.erl, src/osiris_replica.erl, test/osiris_log_SUITE.erl
When a replica is initialising and there is local data but none of
it overlaps with the writer's source data the local stream was not
truncated resulting in an out of order error when the replica received
it's first chunk. This change ensures the entire log is deleted when
there is not overlap.
Fixes #43
=> Fix bug when truncating replica stream with no overlap

src/osiris_log.erl
A retention policy can be evaluated after a stream has been deleted,
it's an asynchronous call to `osiris_retention`, and then crash
because an empty list of segments. This patchs allows the retention
call to complete, doing effectively nothing and avoiding the crash
in the logs
=> Handle empty segment list for retention evaluation

src/osiris.erl, src/osiris_log.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
This will allow decompressing clients to better allocate memory during
decompression etc. Will also enable calculation of the decompressed
size of the stream if that is data we want to track. No validation
of this field is performed.
=> Add uncompressed length to sub batch format

.github/workflows/erlang.yml, .gitignore, BUILD.bazel, Makefile, WORKSPACE.bazel, mk/bazel.mk
This will allow easy consumption of this library by projects using
https://github.com/rabbitmq/bazel-erlang
=> Add a Bazel build

src/osiris_log.erl, test/osiris_SUITE.erl, test/osiris_log_SUITE.erl
Refactoring to better handle cases where previously the `next` offset spec
would try to attach to the eof position even though this can vary depending
on whether the log is being written to during reader init. This would result
in many unexpected_chunk_id exceptions during load.
Also refactoring and simplifying other aspects of reader init to make
code clearer and in some cases faster.
=> Refactoring and bug fixes for osiris_log

src/osiris_log.erl, test/osiris_log_SUITE.erl
The spec of the log overview had the epoch and offset values reversed.
=> Fix EpochOffsets spec

src/osiris_log.erl
When an offset reader wants to attach at a given offset and this offset
is the next offset to be written in the stream there was a race condition
when we first detect the offset is out of range then retry attach with the
`next` offset spec. if a chunk was written in between these two events we
could end up skipping one or more chunks of data.
=> Avoid race condition when attaching at last + 1

.github/workflows/erlang.yml, BUILD.bazel, WORKSPACE.bazel
rules_erlang v2 actually is bazel-erlang v2, but with a more conventional name
=> Use rules_erlang v2 instead of bazel-erlang v1.x

.github/workflows/erlang.yml, BUILD.bazel, src/osiris.erl, src/osiris_bench.erl, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_server_sup.erl, src/osiris_writer.erl, test/osiris_SUITE.erl
There is still a warning for `osiris_replica.erl:542` on Erlang 25. The intention of the callback as-is is not clear to me, so I have not fixed it.
https://erlang.org/documentation/doc-13.0-rc1/lib/stdlib-4.0/doc/html/gen_server.html#Module:format_status-1
=> Fix various dialyzer warnings

src/osiris_log.erl, test/osiris_log_SUITE.erl
As discovered in #68, there is a typo in one of the returned
error atoms.
We stick to "invalid_last_offset_epoch" over "invalid_last_epoch_offset"
because the check that detects an invalid value
in `osiris_log:check_chunk_has_expected_epoch/3` checks for epoch
validity, not offset validity.
This is a potentially breaking change but even in RabbitMQ-related
projects, this specific error was not handled.
=> Make init_reader and init_data_reader use a consistent return value

src/osiris_log.erl
Some file:position/2 operations are subject to race conditions. In particular,
`eof` may position the Fd in the middle of a record being written concurrently.
If that happens, we need to re-position at the nearest record boundry.
Fixes https://github.com/rabbitmq/osiris/issues/73
=> Position Fd at index record boundry

Makefile, src/osiris.erl, src/osiris_replica.erl, src/osiris_util.erl, test/osiris_SUITE.erl
Also use a randomised port selection strategy instead of a linear
scan of the entire port range. This should increase the likelihood of
an unused port being selected the first time even when many replicas
are restarting.
Also refactoring and reformatting to aid readability.
Also unify the osiris_replica log message formats.
=> Set {reuseaddr, true} to allow replicas to reuse listener ports

.github/workflows/rabbitmq-oci.yaml, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_replica_reader.erl, src/osiris_util.erl, test/osiris_log_SUITE.erl
Various osiris_log optimisations, especially around streams with many segments.
Previously we'd always build a full log overview before doing any of, attaching, initialising or evaluating retention. With these optimisations we only scan the index and segment files we need to.
https://github.com/rabbitmq/osiris/issues/70
=> Log overview optimisations

src/osiris_log.erl, test/osiris_log_SUITE.erl
* avoid going through all segments multiple times (after deleting each file) - in practice, there was usually 1 unnecessary loop (because usually we delete 1 segment)
* cheaper `segment_from_index_file` function
This implementation is roughly 50% faster in the most common case (1 segment needs to be deleted).
=> Retention optimisations

src/osiris_util.erl, test/osiris_util_SUITE.erl
file:consult/1 is OK to parse a configuration file with some
TLS settings, but it does not support parsing "complex"
settings like a function to validate the hostname.
This commit introduces a hook so that the calling application
can provide a custom function instead of the default file:consult/1
and this way easily support parsing the app settings.
Fixes #78
Note this PR introduces a breaking change (extra parameter to pass the function in).
=> Add hook for file:consult/1 for TLS replication

src/osiris_replica.erl
Callback Module:format_status(Status) is new in gen_server in OTP 25.
Prior to this commit this function was used nowhere for OTP < 25.
Prior to this commit, this function crashed in OTP 25:
```
(rabbit-2@host)2> rp(sys:get_status(<0.2556.0>)).
{status,<0.2556.0>,
{module,gen_server},
[[{'$initial_call',{osiris_replica,init,1}},
{'$ancestors',[osiris_server_sup,osiris_sup,<0.1693.0>]},
{rand_seed,{#{bits => 58,jump => #Fun<rand.3.34006561>,
next => #Fun<rand.0.34006561>,type => exsss,
uniform => #Fun<rand.1.34006561>,
uniform_n => #Fun<rand.2.34006561>},
[261007605009854015|3188942010446928]}}],
running,<0.1696.0>,[],
[{header,"Status for generic server <0.2556.0>"},
{data,[{"Status",running},
{"Parent",<0.1696.0>},
{"Logged events",[]}]},
{data,[{"State",
"osiris_replica:format_status/1 …
```
=> Fix osiris_replica:format_status/1 crash

src/osiris_tracking.erl
Running
```
java -jar target/stream-perf-test.jar --producer-names="my-producer-%s-%d"
```
for 20 seconds against RabbitMQ server with 2 CPUs.
Prior to this commit 12.3% of CPU time was spent in function `plural/1` 🙈.
Before
```
Summary: published 987863 msg/s, confirmed 987374 msg/s, consumed 987173 msg/s, latency 95th 15 ms, chunk size 4238
```
After
```
Summary: published 1357363 msg/s, confirmed 1356868 msg/s, consumed 1356868 msg/s, latency 95th 11 ms, chunk size 4186
```
Thanks @kjnilsson for spotting this!
=> Fix slow tracking

src/osiris_log.erl
If a stream member is being deleted whilst retention is evaluating
the retention process could crash if there are no index / segment
files.
=> Handle potential retention race condition

WORKSPACE.bazel, src/osiris_replica.erl
Using a customer exit reason triggers the logging of the stack
trace, which is not necessary when reader just stops, e.g.
when the replica reader node shuts down.
References #89, rabbitmq/rabbitmq-server#5393
=> Use normal exit reason on replica reader shutdown

src/osiris.erl, src/osiris_log.erl, src/osiris_writer.erl, test/osiris_SUITE.erl
Else this counter may be incorrect or remain set to -1 until
next time retention runs. As we want to expose this valute to users
we need to ensure it is always correctly initialised. Fixes #98 
This Pr also includes an `osiris:get_stat/1` API to get the committed and first offsets from any member of a stream. Fixes #97
=> Ensure a writer|replica start initialises first offset

WORKSPACE.bazel, src/osiris_replica_reader.erl
Not only on handshake failure.
ML thread: https://groups.google.com/g/rabbitmq-users/c/7zGWzNExxp8/m/9-w6esEZBAAJ
=> Try other addresses for TLS replication on failure

src/osiris.erl, src/osiris_log.erl, src/osiris_log_shared.erl, src/osiris_replica.erl, src/osiris_writer.erl, test/osiris_log_SUITE.erl
1. To avoid blocking the supervisor (which is shared with the writer and all other replicas) this commit moves the initialisation work into handle_continue. osiris_replica:start/2 now does a call into the started process to still block until init work is complete.
2. To avoid replica readers having to check the disk every time they reach `end_of_stream` writers and replicas now share the last chunk id via the shared atomic value avoiding the need to check the disk unless needed to open the next segment file.
These two changes improve the scalability of using multiple streams.
=> osiris_replica: optimisations

WORKSPACE.bazel, src/osiris.erl, src/osiris_ets.erl, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_sup.erl, src/osiris_util.erl, src/osiris_writer.erl, test/osiris_log_SUITE.erl
Cache reader context data in ETS table to avoid process call.
Which could time out during high load.
Bug fixes:
Fixes diverged replica truncation bug.
Fixes bug in acceptor initialisation that would ignore the requested initial_offset passed in the config.
Better handling of suddenly closed TCP connection in replica readers.
=> Cache reader context

src/osiris_log.erl, test/osiris_SUITE.erl
Removes the code setting the `nopush` socket option and leaves that to users of the `osiris_log:send_file` API.
Removes uses of `file:position/2` to maintain read position in the stream and instead keeps this in the read state.
=> Improve small chunk workload throughput

.github/workflows/rabbitmq-oci.yaml
Until https://github.com/bazelbuild/bazel/issues/17128#issuecomment-1370305145 is implemented, there is no clean way to override an erlang package.
So at least let's try doing our best, and just check afterwards that it actually worked.
=> Fix rabbitmq docker image build

src/osiris_replica.erl
This helps reducing the number of `no_available_ports_in_range` errors encountered when starting lots of replicas at once. E.g. after a RabbitMQ nodes start.
Also adding configuration for reuseaddr and listen socket options.
=> Add small backoff when doing replica port scans.

src/osiris_replica.erl, src/osiris_replica_reader.erl
The initialisation function of the replica reader expected `osiris_writer:init_data_reader/3` to generate an exception, but it returns a tagged error instead. This PR tries to handle better the error so the long `badmatch` stacktrace is replaced by a log warning and controlled stop. 
Also `osiris_replica` needs to handle the case on terminate when the socked hasn't yet been initialised, otherwise `inet_tcp:close/1` returns a `function_clause`.
=> Handle errors on replica and replica reader

src/osiris_replica.erl, src/osiris_replica_reader.erl
If starting the reader returns an error, osiris_replica should handle it and stop nicely.
```
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0> ** When Server state == "osiris_replica:format_status/1 crashed"
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0> ** Reason for termination ==
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0> ** {{case_clause,
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0>         {error,
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0>             {writer_unavailable,
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0>                 {child,undefined,#Ref<0.345803779.3209691138.252379>,
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0>                     {osiris_replica_reader,start_link,
2023-07-05 12:00:26.911201+02:00 [error] <0.1717.0> …
```
=> Fix case_clause in osiris_replica_reader

src/osiris.hrl, src/osiris_replica.erl, src/osiris_replica_reader.erl
replica reader: send token earlier
before initiating the log reader. This should reduce the time a given socket listener needs to be open.
=> Replica logging improvements

src/osiris_replica.erl
This is a mostly cosmetic change that improves the error report when `osiris_replica` terminates early. The server state may be `undefined` when terminating if the rpc call to `osiris_writer` fails in the `handle_continue/2` block. See: https://github.com/rabbitmq/osiris/blob/fbe6fa80bcba19db727e4a5b426df456993063c5/src/osiris_replica.erl#L158-L162
=> osiris_replica: Handle undefined state in format_status/1

.github/workflows/rabbitmq-oci.yaml
Now that osiris is a bazel_dep in rabbitmq-server, the override can be simpified
=> Fix OCI workflow for rabbitmq-server@main

.bazelrc
so that our modules publishes can be handled independently of the bazel team
=> Use the additional rabbitmq erlang-packages bzlmod registry

src/osiris_server_sup.erl
Without this change, if a replica was delete when the node was down (and therefore it wasn't immediately deleted), orphaned folders would pile up. With this change, when the node is started again, it will clean up the unneeded folder.
Part of https://github.com/rabbitmq/rabbitmq-server/issues/9282
=> Delete folders of deleted replicas

src/osiris_log.erl, src/osiris_replica.erl, src/osiris_replica_reader.erl, src/osiris_util.erl, src/osiris_writer.erl, test/osiris_log_SUITE.erl
Optimise index scanning using a skip search approach.
This improves worst case index scanning scenarios
by making the scanning to find offset as well as epoch / chunk_id
paris (as part of osiris_log:overview/1) up to 10x faster.
Move reader context caching earlier in writer initialisation
To increase the chance of a replica calling osiris_writer:overview/1
will get the cached reader context instead of having to call into
the writer process.
Unfortunately we can only cache the context after log init but
it can be done before any other work such as tracking recovery.
Make the replica call into the leader process (`osiris_writer:overview/1`) use infinity timeout to avoid cases where writer init takes so long a replica times out and has to be restarted.
osiris_log refactoring and log …
=> Optimise index scanning

src/osiris.erl, src/osiris_log.erl, test/osiris_log_SUITE.erl
To allow readers to read chunks incrementally rather than in one go.
osiris_log:read_chunk_parsed/2 has been updated to use the chunk iterator API as well but with a full chunk read ahead configuration.
osiris_log:chunk_iterator/2 tries to estimate a read ahead amount based on the "credit hint" that can be passed to indicate how many entries are likely to be read in one go.
=> Add chunk iterator API to osiris_log

src/osiris_log.erl, test/osiris_log_SUITE.erl
The chunk_info.size field did not take filter sizes into account which would cause the `next` attach strategy to calculate an incorrect position in the segment file casuing a reader crash.
=> Calculate the correct chunk size when filters are used.

src/osiris_retention.erl
It is possible that osiris_log:evaluate_retention/1 may throw an error, in particular `missing_file` which could occur if an osiris member was deleted whilst an evaluation request was outstanding.
Currently this crashes the evaluation process which isn't a big deal
as it will restart but we'd lose any pending evaluation requests when this happen so it is better to try to avoid that.
=> Be more defensive when evaluating retention.

src/osiris_log.erl
On some systems (windows) a call to file:pread/3 may change the underlying file position resulting in chunks written after a re-init of the tracking data being written at the wrong location.
=> Use a new file handle to recover tracking.

.github/workflows/erlang.yml, src/osiris_log.erl, src/osiris_replica.erl, src/osiris_replica_reader.erl
Avoids "format_status crashed errors in log files"
=> Correctly handle case where replica exits in handle_continue.

src/osiris_replica_reader.erl
In the context of RabbitMQ, if a stream queue is deleted right after being declared, there is a chance that some Osiris processes might not be ready yet at the time the queue is deleted.
In particular, the `osiris_replica_reader` process monitors the given leader (an `osiris_writer` process in the context of a RabbitMQ stream queue) during its `init/1` and that process might be stopped already.
When this happens, here is the crash that is logged:
[error] <0.1548.0> ** Generic server <0.1548.0> terminating
[error] <0.1548.0> ** Last message in was {'DOWN',#Ref<0.1118981177.1281884162.97904>,process,
[error] <0.1548.0>                                <0.1535.0>,noproc}
[error] <0.1548.0> ** When Server state == {state,
[error] <0.1548.0>                          {osiris_log,
[error] …
=> osiris_replica_reader: Stop with `normal` if the leader is already gone during `init/1`

src/osiris_log.erl, src/osiris_util.erl, test/osiris_log_SUITE.erl
Also delete any segment files that do not have any index files that may have been caused by a process crash during retention deletion.
See: https://github.com/rabbitmq/rabbitmq-server/discussions/12054
Refactoring around file listings.
Also a fix to segment counter after recovery with an empty log.
=> osiris_log:overview/1 - fix crash with trailing empty index.

src/osiris_log.erl, test/osiris_log_SUITE.erl
some filesystems (e.g. NFS) create hidden files to deal with deletion of open files. The presence of a file: .nfs000000000000000 would stop the osiris log from initialising.
This commit updates the code to ignore such files and proceed anyway.
=> Ignore unexpected files in the log directory.

test/osiris_SUITE.erl
If it's not defined, try to locate `gmake` then fallback to `make`.
=> osiris_SUITE: Use `$MAKE` if it is defined

src/osiris_replica.erl, src/osiris_replica_reader.erl, src/osiris_util.erl, test/osiris_SUITE.erl
Some environments are IPv6-only or at least strive to be, plus RabbitMQ allows for IPv6-only configuration
in a lot places.
Note that instead of introducing a new transport type (e.g. tcp6 or tcp_ipv6, tls_ipv6), which requires
many scattered changes, this introduces a separate option that is passed to `gen_tcp:listen/2`,
`inet:setopts/2` and such.
CT tests use a new group to avoid interference.
The `rabbitmq.conf` part belongs to the RabbitMQ server repository.
Closes #116.
=> Make it possible to configure IP address family for Osiris replica listeners

src/osiris_replica.erl, src/osiris_replica_reader.erl, test/osiris_SUITE.erl
It is possible that the writer's node could go down in between querying the writer for it's log overview and then starting the replica reader. This commit handles that potentially common scenarion more gracefully.
=> Replica: Handle nodedowns when starting replica reader.

erlang.mk, src/osiris_writer.erl
This seems to increase throughput by ~10% on OTP26 and even more on OTP27. In particular, it seems to solve the performance regression with small messages on OTP 27:
stream-perf-test -s 100 results (single node, everything local): OTP26 as-is: 880k
OTP26, fullsweep_after 0: 940k
OTP27 as-is: 750k
OTP27 fullsweep_after 0: 1M
=> Set fullsweep_after=0 on the writer process

src/osiris_log.erl, test/osiris_log_SUITE.erl
If osiris_replica:parse_chunk ended up parsing an chunk iolist where the first element in the list is exactly 48 bytes (the size of the osiris chunk header) it would end up crashing the call to osiris_log:accept_chunk as this assumed the filter data, when included, would always be in the first list element.
=> Fix bug in replica chunk acceptance when filters are used.

src/osiris_replica.erl, src/osiris_replica_reader.erl
Starting a replica and its reader can temporarily in some cases and environment (e.g. when restarting a node on K8S, when DNS is not sorted out yet). The current logging messages can be misleading and verbose.
This commit tries to avoid crash reports when a replica reader cannot connect to its replica. This is usually a transient issue and the whole crash report does not help much and clutters the log file.
References #186
=> Improve logging during replicat initialization
